In [37]:
import numpy as np
from  scipy.signal import correlate2d
from copy import copy

In [20]:
a = np.asarray([[1,2,3,4],[4,3,2,1],[3,2,1,4],[2,3,4,1]])
k = np.asarray([[1,1,1],[1,2,1],[1,1,1]])

In [48]:
result = np.zeros(tuple([2 * s for s in a.shape]))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        result[i:i+3,j:j+3] += a[i,j] * k
print(result)

[[ 1.  3.  6.  9.  7.  4.  0.  0.]
 [ 5. 11. 17. 18. 14.  5.  0.  0.]
 [ 8. 19. 24. 24. 16.  9.  0.  0.]
 [ 9. 20. 26. 22. 17.  6.  0.  0.]
 [ 5. 12. 18. 19. 11.  5.  0.  0.]
 [ 2.  5.  9.  8.  5.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [52]:
def insert_zeros(r,s):
    zero_inserted = np.zeros((s + 1) * r.shape[0])
    for i in range(r.shape[0]):
        zero_inserted[(s + 1) * i] = r[i]
    return zero_inserted

In [53]:
def deconv(a, k, stride):
    result_1 = np.zeros(tuple([stride * s for s in a.shape]))
    for  i  in range(a.shape[0]):
        ai_zero_inserted = insert_zeros(a[i], stride- 1)
        result_1[stride * i,:] = ai_zero_inserted
    return correlate2d(result_1, k)

In [54]:
result = deconv(a,k,2)

In [55]:
result

array([[ 1.,  1.,  3.,  2.,  5.,  3.,  7.,  4.,  4.,  0.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  4.,  0.],
       [ 5.,  5., 10.,  5., 10.,  5., 10.,  5.,  5.,  0.],
       [ 4.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.,  0.],
       [ 7.,  7., 12.,  5.,  8.,  3.,  8.,  5.,  5.,  0.],
       [ 3.,  6.,  5.,  4.,  3.,  2.,  5.,  8.,  4.,  0.],
       [ 5.,  5., 10.,  5., 10.,  5., 10.,  5.,  5.,  0.],
       [ 2.,  4.,  5.,  6.,  7.,  8.,  5.,  2.,  1.,  0.],
       [ 2.,  2.,  5.,  3.,  7.,  4.,  5.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [38]:
result = np.zeros(tuple([2 * s for s in a.shape]))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        _result = copy(result)
        _result[i:i+3,j:j+3] += a[i,j] * k
        print(_result)

[[1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 2. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 2. 2. 2. 0. 0. 0. 0.]
 [0. 2. 4. 2. 0. 0. 0. 0.]
 [0. 2. 2. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 3. 3. 3. 0. 0. 0.]
 [0. 0. 3. 6. 3. 0. 0. 0.]
 [0. 0. 3. 3. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 4. 4. 4. 0. 0.]
 [0. 0. 0. 4. 8. 4. 0. 0.]
 [0. 0. 0. 4. 4. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 4. 0. 0. 0. 0. 0.]
 [4. 8. 4. 0. 0. 0. 0. 0.]
 [4. 4. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0

In [ ]:
result = np.zeros(tuple([2 * s for s in a.shape]))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        print(i,j)
        result[i:i+3,j:j+3] += a[i,j] * k
print(result)
                 