In [1]:
import numpy as np
from  scipy.signal import correlate2d
from copy import copy

In [2]:
a = np.asarray( [[1,2,3,4,5,6],[4,3,2,1,5,6],[3,2,1,4,5,6],[2,3,4,1,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]],
               dtype=np.float64 )
k = np.asarray( [[1.0,1.0,1.0],
                 [1.0,2.0,1.0],
                 [1.0,1.0,1.0]],
               dtype=np.float64)
print("Kernel")
print(k)
print("Image")
print(a)

Kernel
[[1. 1. 1.]
 [1. 2. 1.]
 [1. 1. 1.]]
Image
[[1. 2. 3. 4. 5. 6.]
 [4. 3. 2. 1. 5. 6.]
 [3. 2. 1. 4. 5. 6.]
 [2. 3. 4. 1. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


In [3]:
result = np.zeros(tuple([2 * s for s in a.shape]))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        result[i:i+3,j:j+3] += a[i,j] * k
print(result)

[[ 1.  3.  6.  9. 12. 15. 11.  6.  0.  0.  0.  0.]
 [ 5. 11. 17. 18. 24. 32. 28. 12.  0.  0.  0.  0.]
 [ 8. 19. 24. 24. 31. 47. 39. 18.  0.  0.  0.  0.]
 [ 9. 20. 26. 22. 32. 44. 39. 18.  0.  0.  0.  0.]
 [ 6. 15. 24. 28. 33. 47. 39. 18.  0.  0.  0.  0.]
 [ 4. 12. 23. 29. 38. 47. 39. 18.  0.  0.  0.  0.]
 [ 2.  7. 14. 21. 28. 35. 28. 12.  0.  0.  0.  0.]
 [ 1.  3.  6.  9. 12. 15. 11.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [6]:
def insert_zeros(r,s):
    zero_inserted = np.zeros((s + 1) * r.shape[0])
    for i in range(r.shape[0]):
        zero_inserted[(s + 1) * i] = r[i]
    return zero_inserted

In [12]:
def deconv(a, k, stride):
    result_1 = np.zeros(tuple([stride * s for s in a.shape]))
    for  i  in range(a.shape[0]):
        ai_zero_inserted = insert_zeros(a[i], stride- 1)
        result_1[stride * i,:] = ai_zero_inserted
    print(result_1)
    return correlate2d(result_1, k)

In [14]:
result = deconv(a,k,1)

[[1. 2. 3. 4. 5. 6.]
 [4. 3. 2. 1. 5. 6.]
 [3. 2. 1. 4. 5. 6.]
 [2. 3. 4. 1. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]


In [15]:
result

array([[ 1.,  3.,  6.,  9., 12., 15., 11.,  6.],
       [ 5., 11., 17., 18., 24., 32., 28., 12.],
       [ 8., 19., 24., 24., 31., 47., 39., 18.],
       [ 9., 20., 26., 22., 32., 44., 39., 18.],
       [ 6., 15., 24., 28., 33., 47., 39., 18.],
       [ 4., 12., 23., 29., 38., 47., 39., 18.],
       [ 2.,  7., 14., 21., 28., 35., 28., 12.],
       [ 1.,  3.,  6.,  9., 12., 15., 11.,  6.]])

In [11]:
result = np.zeros(tuple([2 * s for s in a.shape]))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        _result = copy(result)
        _result[i:i+3,j:j+3] += a[i,j] * k
        print(_result)

[[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 2. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 4. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 3. 3. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 6. 3. 0. 0. 

In [16]:
result = np.zeros(tuple([2 * s for s in a.shape]))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        result[i:i+3,j:j+3] += a[i,j] * k
print(result)
                 

[[ 1.  3.  6.  9. 12. 15. 11.  6.  0.  0.  0.  0.]
 [ 5. 11. 17. 18. 24. 32. 28. 12.  0.  0.  0.  0.]
 [ 8. 19. 24. 24. 31. 47. 39. 18.  0.  0.  0.  0.]
 [ 9. 20. 26. 22. 32. 44. 39. 18.  0.  0.  0.  0.]
 [ 6. 15. 24. 28. 33. 47. 39. 18.  0.  0.  0.  0.]
 [ 4. 12. 23. 29. 38. 47. 39. 18.  0.  0.  0.  0.]
 [ 2.  7. 14. 21. 28. 35. 28. 12.  0.  0.  0.  0.]
 [ 1.  3.  6.  9. 12. 15. 11.  6.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [17]:
from clearn.utils.tensorflow_wrappers.layers import deconv2d
import tensorflow as tf

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/

In [18]:
output_shape = [2 * s for s in a.shape]
output_shape.insert(0,1)
output_shape.append(1)
print(output_shape)

[1, 12, 12, 1]


In [19]:
input_= a
w = k
deconv = tf.nn.conv2d_transpose(input_, w, output_shape=tuple(output_shape), strides=[1, 2, 2, 1])

In [20]:
print(deconv)

Tensor("conv2d_transpose:0", shape=(1, 12, 12, 1), dtype=float64)


In [21]:
def add_batch(t):
    result = np.expand_dims(t,0)
    return result

def add_batch_and_output_dims(t):
    result = np.expand_dims(t,0)
    return np.expand_dims(result,3)

    

In [22]:
tf.reset_default_graph()

print(add_batch_and_output_dims(w).shape)

deconv = tf.nn.conv2d_transpose(tf.convert_to_tensor(add_batch(input_) ),
                                tf.convert_to_tensor(add_batch_and_output_dims(w) ),
                                output_shape=tuple(output_shape),
                                strides=[1, 2, 2, 1]
                               )
with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
    deconv_result = sess.run(deconv)
    print(deconv_result)


(1, 3, 3, 1)


InvalidArgumentError: Conv2DCustomBackpropInput: out_backprop must be 4-dimensional
	 [[node conv2d_transpose (defined at <ipython-input-22-d0e82fa8f0ec>:8) ]]

Errors may have originated from an input operation.
Input Source operations connected to node conv2d_transpose:
 Const (defined at <ipython-input-22-d0e82fa8f0ec>:5)	
 Const_1 (defined at <ipython-input-22-d0e82fa8f0ec>:6)

Original stack trace for 'conv2d_transpose':
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 612, in start
    self.io_loop.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 306, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2923, in _run_cell
    return runner(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3147, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3338, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-d0e82fa8f0ec>", line 8, in <module>
    strides=[1, 2, 2, 1]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2147, in conv2d_transpose
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2218, in conv2d_transpose_v2
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1407, in conv2d_backprop_input
    name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
